### ISSUE TITLE
Check required tools before starting

### ISSUE THREAD

**Issue by wernight** [sk-/optimage#27]
The installation section https://github.com/sk-/optimage#installation does not tell that you need to also install pngcrush, optipng, zopflipng...

When running the tool, it'll tell you that it's missing only after running the first tool, so it'll fail late. It should check early that all required binaries exist.

**Comment by sk-** [comment]
The binaries are optional, as you may only want to optimize pngs or jpegs. I don't want to force installing those optimizers if you are not going to use them.
